# Generated by Django 5.1.6 on 2026-02-14 13:20

import django.db.models.deletion
import django.utils.timezone
import tds_new.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Email do usuário (usado para login)', max_length=254, unique=True, verbose_name='e-mail address')),
                ('invite_token', models.CharField(blank=True, help_text='Token usado no processo de convite de novos usuários', max_length=64, null=True, verbose_name='Token de convite')),
                ('username', models.CharField(blank=True, help_text='Username (preenchido automaticamente com email)', max_length=150, null=True, verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'customUser',
            },
            managers=[
                ('objects', tds_new.models.base.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome da conta/organização', max_length=255, unique=True, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ da organização (opcional)', max_length=32, null=True, verbose_name='CNPJ')),
                ('is_active', models.BooleanField(default=True, help_text='Conta ativa no sistema', verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'conta',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Visualizador')], default='viewer', help_text='Nível de acesso do usuário na conta', max_length=20, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True, help_text='Membership ativo', verbose_name='Ativo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adesão')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tds_new.conta', verbose_name='Conta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'conta_membership',
                'ordering': ['conta', 'user'],
                'indexes': [models.Index(fields=['conta', 'user'], name='conta_membe_conta_i_dcd01e_idx'), models.Index(fields=['user', 'is_active'], name='conta_membe_user_id_f68010_idx')],
                'unique_together': {('conta', 'user')},
            },
        ),
    ]
