# Generated by Django 5.1.6 on 2026-02-15 12:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds_new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Primeiro dia do mês (resultado do time_bucket)', verbose_name='Mês de Referência')),
                ('total_consumo', models.DecimalField(decimal_places=4, help_text='Soma de todas as leituras do mês', max_digits=15, verbose_name='Consumo Total')),
                ('media_diaria', models.DecimalField(decimal_places=4, help_text='Média das leituras do mês', max_digits=15, verbose_name='Média Diária')),
                ('leituras_count', models.IntegerField(help_text='Número de leituras no período', verbose_name='Quantidade de Leituras')),
            ],
            options={
                'verbose_name': 'Consumo Mensal',
                'verbose_name_plural': 'Consumos Mensais',
                'db_table': 'tds_new_consumo_mensal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeituraDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, help_text='Data/hora da leitura (partition key do TimescaleDB)', verbose_name='Timestamp')),
                ('valor', models.DecimalField(decimal_places=4, help_text='Valor da leitura', max_digits=15, verbose_name='Valor')),
                ('unidade', models.CharField(help_text='Unidade de medida (kWh, m³, L, °C, etc)', max_length=10, verbose_name='Unidade')),
                ('payload_raw', models.JSONField(blank=True, help_text='Payload JSON completo recebido via MQTT (opcional)', null=True, verbose_name='Payload Raw')),
            ],
            options={
                'verbose_name': 'Leitura de Dispositivo',
                'verbose_name_plural': 'Leituras de Dispositivos',
                'db_table': 'tds_new_leitura_dispositivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(help_text='Código único do gateway dentro da conta', max_length=30, verbose_name='Código')),
                ('mac', models.CharField(help_text='Endereço MAC no formato aa:bb:cc:dd:ee:ff (usado como identificador MQTT)', max_length=17, verbose_name='MAC Address')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada geográfica', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada geográfica', max_digits=9, null=True, verbose_name='Longitude')),
                ('qte_max_dispositivos', models.IntegerField(default=8, help_text='Capacidade máxima de dispositivos conectados (padrão: 8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)], verbose_name='Quantidade Máxima de Dispositivos')),
                ('is_online', models.BooleanField(default=False, help_text='Indica se o gateway está conectado ao broker MQTT', verbose_name='Online')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Data/hora da última telemetria recebida', null=True, verbose_name='Última Comunicação')),
                ('firmware_version', models.CharField(blank=True, help_text='Versão do firmware instalado no gateway', max_length=20, null=True, verbose_name='Versão do Firmware')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tds_new.conta', verbose_name='Conta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(help_text='Código único do dispositivo dentro do gateway (ex: D01, D02)', max_length=20, verbose_name='Código')),
                ('mac', models.CharField(blank=True, help_text='MAC address (obrigatório apenas para dispositivos WiFi/Ethernet direto)', max_length=17, null=True, verbose_name='MAC Address')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('MEDIDOR', 'Medidor de Consumo'), ('SENSOR', 'Sensor'), ('ATUADOR', 'Atuador')], default='MEDIDOR', max_length=10, verbose_name='Tipo')),
                ('register_modbus', models.IntegerField(blank=True, help_text='Registro Modbus a ser lido (1-65535)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Registro Modbus')),
                ('slave_id', models.IntegerField(blank=True, help_text='ID do dispositivo no barramento Modbus (1-247)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(247)], verbose_name='Slave ID')),
                ('modo', models.CharField(choices=[('AUTO', 'Automático'), ('MANUAL', 'Manual')], default='AUTO', max_length=10, verbose_name='Modo de Operação')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Manutenção')], default='ATIVO', max_length=15, verbose_name='Status')),
                ('val_alarme_dia', models.DecimalField(blank=True, decimal_places=4, help_text='Valor limite para disparo de alarme diário', max_digits=15, null=True, verbose_name='Valor de Alarme Diário')),
                ('val_alarme_mes', models.DecimalField(blank=True, decimal_places=4, help_text='Valor limite para disparo de alarme mensal', max_digits=15, null=True, verbose_name='Valor de Alarme Mensal')),
                ('is_online', models.BooleanField(default=False, help_text='Indica se o dispositivo está respondendo', verbose_name='Online')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Data/hora da última leitura recebida', null=True, verbose_name='Última Leitura')),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versão do Firmware')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tds_new.conta', verbose_name='Conta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('gateway', models.ForeignKey(help_text='Gateway ao qual o dispositivo está conectado', on_delete=django.db.models.deletion.CASCADE, to='tds_new.gateway', verbose_name='Gateway')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['gateway', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('mac_address', models.CharField(help_text='MAC address do dispositivo (formato aa:bb:cc:dd:ee:ff)', max_length=17, verbose_name='MAC Address')),
                ('certificate_pem', models.TextField(help_text='Certificado X.509 no formato PEM (-----BEGIN CERTIFICATE-----)', verbose_name='Certificado PEM')),
                ('private_key_pem', models.TextField(blank=True, help_text='Chave privada RSA no formato PEM (armazenamento opcional - use com cuidado!)', null=True, verbose_name='Chave Privada PEM')),
                ('serial_number', models.CharField(help_text='Número de série do certificado (único globalmente)', max_length=50, unique=True, verbose_name='Serial Number')),
                ('expires_at', models.DateTimeField(help_text='Data/hora de expiração do certificado', verbose_name='Data de Expiração')),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora de emissão do certificado', verbose_name='Data de Emissão')),
                ('is_revoked', models.BooleanField(default=False, help_text='Indica se o certificado foi revogado (bloqueado no broker MQTT)', verbose_name='Revogado')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Data/hora da revogação', null=True, verbose_name='Data de Revogação')),
                ('revoke_reason', models.CharField(blank=True, choices=[('COMPROMISED', 'Comprometido/Roubado'), ('SUPERSEDED', 'Substituído por novo certificado'), ('CESSATION', 'Dispositivo descontinuado'), ('KEY_COMPROMISE', 'Chave privada comprometida'), ('AFFILIATION_CHANGED', 'Mudança de propriedade'), ('OTHER', 'Outro motivo')], max_length=30, null=True, verbose_name='Motivo da Revogação')),
                ('revoke_notes', models.TextField(blank=True, help_text='Detalhes adicionais sobre a revogação', null=True, verbose_name='Observações da Revogação')),
                ('renewal_scheduled', models.BooleanField(default=False, help_text='Indica se a renovação via OTA foi agendada', verbose_name='Renovação Agendada')),
                ('renewal_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Renovação Agendada')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tds_new.conta', verbose_name='Conta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Certificado de Dispositivo',
                'verbose_name_plural': 'Certificados de Dispositivos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conta', 'mac_address'], name='tds_new_cer_conta_i_02650e_idx'), models.Index(fields=['serial_number'], name='tds_new_cer_serial__692203_idx'), models.Index(fields=['mac_address', 'is_revoked'], name='tds_new_cer_mac_add_1a96d5_idx'), models.Index(fields=['expires_at'], name='tds_new_cer_expires_ea6561_idx'), models.Index(fields=['is_revoked'], name='tds_new_cer_is_revo_9a2006_idx'), models.Index(fields=['renewal_scheduled', 'renewal_date'], name='tds_new_cer_renewal_4b318b_idx')],
                'unique_together': {('conta', 'mac_address')},
            },
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['conta', 'is_online'], name='tds_new_gat_conta_i_b1b4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['conta', 'mac'], name='tds_new_gat_conta_i_e8f686_idx'),
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['conta', 'codigo'], name='tds_new_gat_conta_i_640742_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gateway',
            unique_together={('conta', 'codigo'), ('conta', 'mac')},
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['conta', 'gateway', 'status'], name='tds_new_dis_conta_i_4e5f39_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['conta', 'mac'], name='tds_new_dis_conta_i_ffd244_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['gateway', 'codigo'], name='tds_new_dis_gateway_32b180_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dispositivo',
            unique_together={('gateway', 'codigo')},
        ),
    ]
