# Generated by Django 5.1.6 on 2026-02-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds_new', '0002_consumomensal_leituradispositivo_gateway_dispositivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadodevice',
            name='csr_pem',
            field=models.TextField(blank=True, help_text='Certificate Signing Request enviado pelo dispositivo. Mantido para auditoria. O dispositivo gera o par de chaves internamente.', null=True, verbose_name='CSR PEM'),
        ),
        migrations.AddField(
            model_name='certificadodevice',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identidade lógica MQTT do dispositivo (ex: AA0011). Preenchido durante o provisionamento.', max_length=20, null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='certificadodevice',
            name='fingerprint_sha256',
            field=models.CharField(blank=True, help_text='Hash SHA-256 do certificado (ex: AA:BB:CC:...). Calculado automaticamente.', max_length=95, null=True, verbose_name='Fingerprint SHA-256'),
        ),
        migrations.AddField(
            model_name='certificadodevice',
            name='gateway',
            field=models.ForeignKey(blank=True, help_text='Gateway ao qual este certificado pertence (opcional — pode ser vinculado após alocação)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='tds_new.gateway', verbose_name='Gateway Associado'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identidade lógica MQTT gravada na NVS de fábrica (ex: AA0011). Usada como ClientID no broker e como base do gateway_code.', max_length=20, null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='gateway_code',
            field=models.CharField(blank=True, help_text="Código derivado em runtime pelo firmware: '{device_id}-{LAST4HEX_MAC}' (ex: AA0011-E1F2). Preenchido pelo backend na primeira conexão MQTT.", max_length=50, null=True, verbose_name='Gateway Code'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='hardware_version',
            field=models.CharField(blank=True, help_text='Revisão de hardware gravada na NVS de fábrica (ex: 1.0)', max_length=20, null=True, verbose_name='Versão de Hardware'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo do hardware gravado na NVS de fábrica (ex: DCU-1800)', max_length=30, null=True, verbose_name='Modelo de Hardware'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Identidade física irrevogável gravada na NVS de fábrica (ex: AA0011). Vinculada ao hardware — nunca muda mesmo se device_id mudar.', max_length=50, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='certificadodevice',
            name='private_key_pem',
            field=models.TextField(blank=True, help_text='[LEGADO — NÃO USE] A chave privada é gerada pelo dispositivo e nunca deve ser armazenada no servidor. Campo mantido apenas para compatibilidade histórica.', null=True, verbose_name='Chave Privada PEM [LEGADO]'),
        ),
        migrations.AddIndex(
            model_name='certificadodevice',
            index=models.Index(fields=['device_id'], name='tds_new_cer_device_id_idx'),
        ),
        migrations.AddIndex(
            model_name='certificadodevice',
            index=models.Index(fields=['gateway'], name='tds_new_cer_gateway_idx'),
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['device_id'], name='tds_new_gw_device_id_idx'),
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['serial_number'], name='tds_new_gw_serial_idx'),
        ),
    ]
